// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'coordinatesBox': string;
  'coordinatesBoxContainer': string;
  'horPosition': string;
  'vertPosition': string;
}
export const cssExports: CssExports;
export default cssExports;
