// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'legendBoard': string;
  'textLine': string;
}
export const cssExports: CssExports;
export default cssExports;
