// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'crossGuide': string;
  'guide': string;
  'horizontal': string;
  'label': string;
  'rotate': string;
  'rotate2': string;
  'vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
