// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty-span': string;
  'list_hor-enter': string;
  'list_hor-enter-active': string;
  'list_hor-leave-active': string;
  'list_hor-leave-to': string;
  'list_vert-enter': string;
  'list_vert-enter-active': string;
  'list_vert-leave-active': string;
  'list_vert-leave-to': string;
}
export const cssExports: CssExports;
export default cssExports;
